# Generated by Django 5.2.5 on 2026-01-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
    ]
